#!/usr/bin/python3

import math
import sys

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def find_prime_factors(number):
    for i in range(2, number):
        if number % i == 0 and is_prime(i) and is_prime(number // i):
            return i, number // i
    return None, None

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor1, factor2 = find_prime_factors(number)
            print(f"{number}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)

